<?php

namespace App\Http\Controllers\PropertiesController;

//use Illuminate\Http\Request;
use Inertia\Inertia;
use Inertia\Response;

class PropertiesForRentController extends BasePropertiesController
{
    public function index(): Response
    {
        return Inertia::render('PropertiesForRent');
    }

    protected function queryAll()
    {
        parent::queryAll(); // TODO: Change the autogenerated stub
    }
}
